### ISSUE TITLE
Does this plugin take care of version code of `pubspec.version`?

### ISSUE THREAD

**Issue by async3619** [zeshuaro/semantic-release-pub#152]
In [flutter docs](https://docs.flutter.dev/deployment/android#updating-the-apps-version-number), they're saying we should specify _version code_ in `version` property of pubspec.yml in this term:

```yaml
version: 1.0.0+1
#              ^ <-- this is the version code
```

Would this plugin take care this by increasing version code on each release? if wouldn't, I'll create a PR fixing this issue.

**Comment by zeshuaro** [comment]
Thanks for the issue. But which section of the docs mentions that the version code should be specified? I also believe it's actually the build number and it's optional:

> version: 1.0.0+1
> The version number is three numbers separated by dots, such as 1.0.0 in the example above, followed by an **optional build number** such as 1 in the example above, separated by a +.

Another note is that I don't think `semantic-release` supports bumping this value, as I don't think this belongs to any of the [release types](commit-analyzer)?

**Comment by async3619** [comment]
oh sorry for misleading btw It seems like not a required thing but they recommend to add it since we don't have any of methods to check given semver is prior or not without versionCode. ([check this](https://developer.android.com/studio/publish/versioning#versionvalues))

and yeah there's no such method to bump that value with semantic-release but I think we could parse that value and increase by 1 for every version bump

**Comment by zeshuaro** [comment]
Right, I think your proposed solution also makes sense. Feel free to raise a PR if you're interested in implementing this.

**Comment by async3619** [comment]
thanks a lot 👍 

btw I've tried to publish apk files without versionCode but I've failed to install it on actual device with error message describing conflict version information

I'll make PR about it as soon as possible
