### ISSUE TITLE
[FEATURE] Integration of dart_apitool

### ISSUE THREAD

**Issue by Jannik-dev** [zeshuaro/semantic-release-pub#466]
### What kind of feature are you missing?

To reduce false labels of commits, an integration of [dart_apitool](https://pub.dev/packages/dart_apitool) would be nice.
It can detect source compatibility and could function as a safety net.

The following actions could be taken:
![image](https://github.com/user-attachments/assets/58510a07-3003-40a2-8d25-a0cc5ec437b1)

`Error` should reject a commit, because it has the wrong label.
`Info` should tell the user that `dart_apitool` could not detect any incompatibilities, and the user should double-check that it is correct. This can be the case if the commit produces a behavior change, which is considered breaking.

**Comment by zeshuaro** [comment]
How does this differ to using semantic commit conventions?

**Comment by Jannik-dev** [comment]
It does not differ, but it assists. The labeling process of commits is manual and therefore errors could be introduced. `dart_apitool` can catch some of these issues (source, but not behavioral compatibility).

For example, you change the method `double calculate()` to `int calculate()` and you forget the breaking change label of your commit, and it looks something like `feat: change return type`. `dart_apitool` can detect that this is a breaking change, and it could be implemented that it checks if the commit has been marked as such.

**Comment by zeshuaro** [comment]
I see, I would say that integrating with this tool is beyond what this plugin is designed to offer, which is to publish a Dart/Flutter package onto the package registry. And it belongs to a different step within the semantic release execution cycle, so I think it should be built as a separate plugin.

The other way I see how this tool is more suitable might be integrating into the PR merge checks. Having this tool to run in PRs to ensure that the correct semantic commit is used can ensure that the right release type is determined when run with semantic release.
